services:
  postgres:
    image: postgres:16-alpine
    container_name: feature_flags_db
    ports:
      - '5431:5432' # Mapeamento de porta para o postgres utilizar a porta 5431 na máquina host (caso a 5432 já esteja em uso)
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: feature_flags_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência de dados
    networks:
      - feature_flags_network

  # Banco de dados para testes e2e
  postgres_test:
    image: postgres:16-alpine
    container_name: feature_flags_test_db
    ports:
      - '5434:5432' # Utilizei a mesma porta para local e para o docker
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: feature_flags_test_db # Nome diferente
    networks:
      - feature_flags_network

  # 2. SERVIÇO DE BACKEND (NestJS)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend # Caminho relativo dentro do contexto
    container_name: feature_flags_backend
    ports:
      - '3000:3000'
    env_file:
      - .env.backend
    environment:
      # O Docker conecta ao host 'postgres' local seria localhost
      DATABASE_URL: postgresql://admin:adminpassword@postgres:5432/feature_flags_db?schema=public
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - feature_flags_network

  # 3. SERVIÇO DE FRONTEND (Astro SSR)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: feature_flags_frontend
    ports:
      - '4321:4321'
    environment:
      INTERNAL_API_URL: http://backend:3000
      PORT: 4321
    depends_on:
      - backend
    networks:
      - feature_flags_network

volumes:
  postgres_data:

networks:
  feature_flags_network:
    driver: bridge
