services:
  postgres:
    image: postgres:16-alpine
    container_name: feature_flags_db
    ports:
      - '5431:5432' # Mapeamento de porta para o postgres utilizar a porta 5431 na máquina host (caso a 5432 já esteja em uso)
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: feature_flags_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência de dados
    networks:
      - feature_flags_network

  # 2. SERVIÇO DE BACKEND (NestJS)
  backend:
    build:
      # Contexto é a raiz do monorepo (onde está o docker-compose.yml)
      context: .
      dockerfile: backend/Dockerfile.backend # Caminho relativo dentro do contexto
    container_name: feature_flags_backend
    ports:
      - '3000:3000'
    env_file:
      - .env.backend
    environment:
      # O backend agora se conecta ao host 'postgres'
      DATABASE_URL: postgresql://admin:adminpassword@postgres:5432/feature_flags_db?schema=public
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - feature_flags_network

  # 3. SERVIÇO DE FRONTEND (Astro SSR)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: feature_flags_frontend
    # Mapeamos a porta do contêiner (4321) para a porta do host (4321)
    ports:
      - '4321:4321'
    environment:
      # O Frontend precisa saber onde está o Backend.
      # Deve ser acessível de fora (localhost) ou via rede interna
      # No modo SSR, o Astro faz a chamada de API no Node.js
      # O host da API para o Node (SSR) dentro do Docker é o NOME DO SERVIÇO:
      INTERNAL_API_URL: http://backend:3000 # <-- ESSENCIAL!
      PORT: 4321
    depends_on:
      - backend
    networks:
      - feature_flags_network

volumes:
  postgres_data:

networks:
  feature_flags_network:
    driver: bridge
